### ISSUE TITLE
OBT /UTC drift problem in an_downsample

### ISSUE THREAD

**Issue by frejon** [frejon/Lapdog_GIT#10]
Downsampling low frequency measurements
Error at loop step 28 or  foutarr{}(2701), file /data/rosetta/LAP_ARCHIVE/RO-C-RPCLAP-5-1601-DERIV-V0.9/2016/JAN/D19/RPCLAP_20160119_120205_914_I1L.TAB
ans =

    'MATLAB:badsubscript'

ans =

    'Index in position 1 exceeds array bounds (must not exceed 2700).'

an_downsample, 330,analysis, 93,rerunlapdog_test, 399,macrono1=802, 2=802

**Comment by frejon** [comment]
between OBT:
411825648.12102  and  411868717.38633
and UTC
    '2016-01-19T12:02:10.598014'    '2016-01-19T23:59:59.992035'
an interval of 11.9637 hours,
there is a drift between UTC & OBT of 0.0108 seconds. There is simply a larger span of seconds in the OBT than an_downsample expects.

Because of this, several measurements in RO-C-RPCLAP-5-1601-DERIV-V0.9/2016/JAN/D19/RPCLAP_20160119_120205_914_I1L.TAB

end up on the wrong side of intervals, and more importantly, one or two measurements end up on the next day, triggering the error.

I guess fixing this error should be by converting OBT or UTC to ET via SPICE, and then doing the "inter" interval finding algorithm with this new time-vector.

**Comment by ErikPGJ** [comment]
Is still unresolved?

**Comment by frejon** [comment]
yep
