### ISSUE TITLE
För många NPL-filer i NPL_tabindex?

### ISSUE THREAD

**Issue by ErikPGJ** [frejon/Lapdog_GIT#11]
9b538d7, 2016-02-25--27

För många NPL-filer i NPL_tabindex? En verkar vara dubbel.

ans =

lapdog: generate LBL files....

Saving pre-createLBL MATLAB workspace+globals in "/home/data/ROSETTA/datasets/EXT1_2016-02-25--27/RO-C-RPCLAP-5-EXT1-DERIV-V1.0/pre_createLBL_workspace.mat"
    Done: 7 s (elapsed wall time)
Saving pre-createLBL MATLAB "index" in "/home/data/ROSETTA/datasets/EXT1_2016-02-25--27/RO-C-RPCLAP-5-EXT1-DERIV-V1.0/pre_createLBL_workspace.index.*"
    Done: 7 s (elapsed wall time)
lapdog: createLBL exception: Expected existing regular file (or symlink to regular file) "/home/data/ROSETTA/datasets/EXT1_2016-02-25--27/RO-C-RPCLAP-5-EXT1-DERIV-V1.0/2016/FEB/D26/RPCLAP_20160226_000030_914_NPL.TAB" can not be found.
row 142, /home/erjo/work_files/ROSETTA/Lapdog_GIT/+EJ_library/+utils/assert.m: assert.file_exists
row 197, /home/erjo/work_files/ROSETTA/Lapdog_GIT/+createLBL/create_OBJTABLE_LBL_file.m: create_OBJTABLE_LBL_file
row 427, /home/erjo/work_files/ROSETTA/Lapdog_GIT/+createLBL/create_LBL_files.m: create_LBL_files
row 325, /home/erjo/work_files/ROSETTA/Lapdog_GIT/createLBL.m: createLBL
row 115, /home/erjo/work_files/ROSETTA/Lapdog_GIT/main.m: main
Aborting LBL file for NPL_tabindex - Continuing
create_LBL_files: 9 s (elapsed wall time)

>> format long
>> {NPL_tabindex.fname}'

ans = 

    '/home/data/ROSETTA/datasets/EXT1_2016-02-26/RO-C-RPCLAP-5-EXT1-DERIV-V1.0/2016/FEB/D26/RPCLAP_20160226_000030_914_NPL.TAB'    
    '/home/data/ROSETTA/datasets/EXT1_2016-02-26/RO-C-RPCLAP-5-EXT1-DERIV-V1.0/2016/FEB/D26/RPCLAP_20160226_120206_805_NPL.TAB'    
    '/home/data/ROSETTA/datasets/EXT1_2016-02-25--27/RO-C-RPCLAP-5-EXT1-DERIV-V1.0/2016/FEB/D25/RPCLAP_20160225_000030_914_NPL.TAB'
    '/home/data/ROSETTA/datasets/EXT1_2016-02-25--27/RO-C-RPCLAP-5-EXT1-DERIV-V1.0/2016/FEB/D26/RPCLAP_20160226_000000_914_NPL.TAB'
    '/home/data/ROSETTA/datasets/EXT1_2016-02-25--27/RO-C-RPCLAP-5-EXT1-DERIV-V1.0/2016/FEB/D26/RPCLAP_20160226_120206_805_NPL.TAB'
    '/home/data/ROSETTA/datasets/EXT1_2016-02-25--27/RO-C-RPCLAP-5-EXT1-DERIV-V1.0/2016/FEB/D27/RPCLAP_20160227_000414_914_NPL.TAB'

Finns bara fyra filer:
RO-C-RPCLAP-5-EXT1-DERIV-V1.0/2016/FEB/D25/RPCLAP_20160225_000030_914_NPL.TAB
RO-C-RPCLAP-5-EXT1-DERIV-V1.0/2016/FEB/D26/RPCLAP_20160226_000000_914_NPL.TAB
RO-C-RPCLAP-5-EXT1-DERIV-V1.0/2016/FEB/D26/RPCLAP_20160226_120206_805_NPL.TAB
RO-C-RPCLAP-5-EXT1-DERIV-V1.0/2016/FEB/D27/RPCLAP_20160227_000414_914_NPL.TAB

**Comment by ErikPGJ** [comment]
Får inte detta fel för feb 2016-arkiv.

**Comment by frejon** [comment]
Fixed in commit fffa8205fee0ebdbba8c63c70c080dac28913643
