### ISSUE TITLE
Kraschar för endagsarkiv 2014-05-09 (commit bf1e0a0)

### ISSUE THREAD

**Issue by ErikPGJ** [frejon/Lapdog_GIT#13]
Analysing sweeps
601 bad smoothening performance
Outputting Science
printing /home/data/ROSETTA/datasets/DPS1/RO-C-RPCLAP-5-DPS1-DERIV-V0.1/2014/MAY/D09/RPCLAP_20140509_152300_506_USC.TAB, mode: vz
printing /home/data/ROSETTA/datasets/DPS1/RO-C-RPCLAP-5-DPS1-DERIV-V0.1/2014/MAY/D09/RPCLAP_20140509_152300_506_NPL.TAB, mode: vz
Downsampling low frequency measurements
Generating spectra
Error at loop step 1 and fout{}(),obs 108, file /home/data/ROSETTA/datasets/DPS1/RO-C-RPCLAP-5-DPS1-DERIV-V0.1/2014/MAY/D09/RPCLAP_20140509_213236_503_V1H.TAB, outputfile /home/data/ROSETTA/datasets/DPS1/RO-C-RPCLAP-5-DPS1-DERIV-V0.1/2014/MAY/D09/RPCLAP_20140509_213236_PSD_V1H.TABMATLAB:UndefinedFunction
Undefined function or variable "freq".
an_hf, 379,
analysis, 129,

**Comment by frejon** [comment]
Erik, test if this bug still exists with the latest commit. If not, close the issue.

**Comment by ErikPGJ** [comment]
Seems to work. Danke sehr.
