### ISSUE TITLE
an_NPLprint: "Error: Deleting of duplicate USC_TABINDEX failed" (Besläktat med issue #15?!!)

### ISSUE THREAD

**Issue by ErikPGJ** [frejon/Lapdog_GIT#16]
analysis.m kraschar för ESC2 (2015-03-11 -- 2015-06-30).
MATLAB R2016a. Senast använda Fredrik-commit: b3aca88

Besläktat med issue #15 ?!!

printing /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-05-14/RO-C-RPCLAP-5-ESC2-DERIV-V2.0/2015/JUN/D30/RPCLAP_20150630_000208_807_USC.TAB, mode: vz
printing /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-05-14/RO-C-RPCLAP-5-ESC2-DERIV-V2.0/2015/JUN/D30/RPCLAP_20150630_000208_807_NPL.TAB, mode: vz
Downsampling low frequency measurements
macrono1=801, 2=801 
printing /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-05-14/RO-C-RPCLAP-5-ESC2-DERIV-V2.0/2015/MAY/D20/RPCLAP_20150520_151719_801_EFL.TAB, macro: 801
macrono1=802, 2=802 
printing /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-05-14/RO-C-RPCLAP-5-ESC2-DERIV-V2.0/2015/MAY/D20/RPCLAP_20150520_171719_802_EFL.TAB, macro: 802
macrono1=802, 2=802 
printing /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-05-14/RO-C-RPCLAP-5-ESC2-DERIV-V2.0/2015/MAY/D28/RPCLAP_20150528_110359_802_EFL.TAB, macro: 802
printing /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-05-14/RO-C-RPCLAP-5-ESC2-DERIV-V2.0/2015/MAY/D20/RPCLAP_20150520_151719_801_USC.TAB, mode: vfloat
printing /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-05-14/RO-C-RPCLAP-5-ESC2-DERIV-V2.0/2015/MAY/D20/RPCLAP_20150520_151719_801_NPL.TAB, mode: vfloat
Error at loop step 12 or  foutarr{}(1750), file /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-05-14/RO-C-RPCLAP-5-ESC2-DERIV-V2.0/2015/MAY/D20/RPCLAP_20150520_151719_801_V2L.TAB
ans =

MATLAB:badsubscript

ans =

Index exceeds matrix dimensions.

an_NPLprint, 51,an_downsample, 505,analysis, 107,lapdog, 117,@()lapdog(calib1Path,missionPhaseNameAbbrev,pdsMissionCalendar), 92,call_function_pointer, 144,lapdog_convention_wrapper, 125,run_lapdog, 94,Generating spectra
Deleting duplicates in USC_TABINDEX 
Error: Deleting of duplicate USC_TABINDEX failed 

ans =

MATLAB:subsdeldimmismatch

ans =

Matrix index is out of range for deletion.

analysis, 160; lapdog, 117; @()lapdog(calib1Path,missionPhaseNameAbbrev,pdsMissionCalendar), 92; call_function_pointer, 144; lapdog_convention_wrapper, 125; run_lapdog, 94; lapdog: generate LBL files....
Saving MATLAB workspace+globals

**Comment by frejon** [comment]
Can't reproduce error message on the same archive with Matlab R2015b on latest commit.
