### ISSUE TITLE
Error at loop step 10 or  foutarr{}(2701), /.../RPCLAP_20160119_120205_914_I1L.TAB

### ISSUE THREAD

**Issue by ErikPGJ** [frejon/Lapdog_GIT#23]
Kraschar EXT1
Kraschar inte för ASTx, PRL, ESCx, EXT2, EXT3
Commit 0f8f173

=========================================================================

printing /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-05-22/RO-C-RPCLAP-5-EXT1-DERIV-V2.0/2016/APR/D05/RPCLAP_20160405_130359_926_USC.TAB, mode: vz
printing /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-05-22/RO-C-RPCLAP-5-EXT1-DERIV-V2.0/2016/APR/D05/RPCLAP_20160405_130359_926_NED.TAB, mode: vz
Downsampling low frequency measurements
Error at loop step 10 or  foutarr{}(2701), file /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-05-22/RO-C-RPCLAP-5-EXT1-DERIV-V2.0/2016/JAN/D19/RPCLAP_20160119_120205_914_I1L.TAB
ans =

MATLAB:badsubscript

ans =

Index exceeds matrix dimensions.

an_downsample, 339,analysis, 93,lapdog, 117,@()lapdog(calib1Path,missionPhaseNameAbbrev,pdsMissionCalendar), 92,call_function_pointer, 144,lapdog_convention_wrapper, 125,run_lapdog, 94,macrono1=802, 2=802 
printing /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-05-22/RO-C-RPCLAP-5-EXT1-DERIV-V2.0/2016/JAN/D15/RPCLAP_20160115_113213_802_EFL.TAB, macro: 802
macrono1=802, 2=802 
printing /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-05-22/RO-C-RPCLAP-5-EXT1-DERIV-V2.0/2016/JAN/D17/RPCLAP_20160117_000413_802_EFL.TAB, macro: 802
macrono1=802, 2=802

**Comment by ErikPGJ** [comment]
Footnote: Maybe unimportant, but there is no LBL file for the corresponding
RO-C-RPCLAP-5-EXT1-DERIV2-V1.0/DATA/DERIVED/2016/JAN/D19/LAP_20160119_120205_32S_I1D.TAB
which implies that it is not in the corresponding variable used by createLBL.

**Comment by frejon** [comment]
See issue #10

**Comment by frejon** [comment]
should be fixed with latest commit #3733ee7
