### ISSUE TITLE
Saknade USC-filer; Expected existing regular file (or symlink to regular file) "/...//RPCLAP_20160715_020746_615_USC.TAB" can not be found.

### ISSUE THREAD

**Issue by ErikPGJ** [frejon/Lapdog_GIT#24]
Commit <=0f8f173 (ung. iaf)
Kraschar för EXT3.
Kraschar ej för ASTx, PRL, ESCx, EXT2.

Krasch (assertion) i ~createLBL som hintar om att USC_tabindex innehåller två filer som inte finns/skapats på disk. Fel i "Deleting duplicates in USC_TABINDEX "?

Deleting duplicates in USC_TABINDEX 
Saving MATLAB workspace+globals
    Saving MATLAB variable "index" (1916683192 bytes) in "/amd/nas24/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-05-22/RO-C-RPCLAP-5-EXT3-DERIV-V2.0/pre_createLBL_workspace.index.*"
    Done saving variables to disk: 30 s (elapsed wall time)
======== An exception has occurred ========
Exception.message    = "Expected existing regular file (or symlink to regular file) "/amd/nas24/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-05-22/RO-C-RPCLAP-5-EXT3-DERIV-V2.0/2016/JUL/D15/RPCLAP_20160715_020746_615_USC.TAB" can not be found."
Exception.identifier = ""
row 142, /amd/hem/export/home/erjo/lapdog_copy1/+EJ_library/+utils/assert.m: assert.file_exists
row 196, /amd/hem/export/home/erjo/lapdog_copy1/+createLBL/create_OBJTABLE_LBL_file.m: create_OBJTABLE_LBL_file
row 329, /amd/hem/export/home/erjo/lapdog_copy1/+createLBL/create_LBL_files.m: create_LBL_files
row 227, /amd/hem/export/home/erjo/lapdog_copy1/createLBL.m: createLBL
row 113, /home/erjo/matlab_copy/+erikpgjohansson/+ro/rerun_analysis_createLBL.m: rerun_analysis_createLBL___INTERNAL
row  34, /home/erjo/matlab_copy/+erikpgjohansson/+ro/rerun_analysis_createLBL.m: @()rerun_analysis_createLBL___INTERNAL(pdDatasetPath,ldDatasetPath,selectedSegments)
row 144, /home/erjo/matlab_copy/+erikpgjohansson/+ro/lapdog_convention_wrapper.m: call_function_pointer
row 125, /home/erjo/matlab_copy/+erikpgjohansson/+ro/lapdog_convention_wrapper.m: lapdog_convention_wrapper
row  33, /home/erjo/matlab_copy/+erikpgjohansson/+ro/rerun_analysis_createLBL.m: rerun_analysis_createLBL
Aborting LBL file for USC_tabindex - Continuing
======== An exception has occurred ========
Exception.message    = "Expected existing regular file (or symlink to regular file) "/amd/nas24/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-05-22/RO-C-RPCLAP-5-EXT3-DERIV-V2.0/2016/JUL/D15/RPCLAP_20160715_033202_417_USC.TAB" can not be found."
Exception.identifier = ""
row 142, /amd/hem/export/home/erjo/lapdog_copy1/+EJ_library/+utils/assert.m: assert.file_exists
row 196, /amd/hem/export/home/erjo/lapdog_copy1/+createLBL/create_OBJTABLE_LBL_file.m: create_OBJTABLE_LBL_file
row 329, /amd/hem/export/home/erjo/lapdog_copy1/+createLBL/create_LBL_files.m: create_LBL_files
row 227, /amd/hem/export/home/erjo/lapdog_copy1/createLBL.m: createLBL
row 113, /home/erjo/matlab_copy/+erikpgjohansson/+ro/rerun_analysis_createLBL.m: rerun_analysis_createLBL___INTERNAL
row  34, /home/erjo/matlab_copy/+erikpgjohansson/+ro/rerun_analysis_createLBL.m: @()rerun_analysis_createLBL___INTERNAL(pdDatasetPath,ldDatasetPath,selectedSegments)
row 144, /home/erjo/matlab_copy/+erikpgjohansson/+ro/lapdog_convention_wrapper.m: call_function_pointer
row 125, /home/erjo/matlab_copy/+erikpgjohansson/+ro/lapdog_convention_wrapper.m: lapdog_convention_wrapper
row  33, /home/erjo/matlab_copy/+erikpgjohansson/+ro/rerun_analysis_createLBL.m: rerun_analysis_createLBL
Aborting LBL file for USC_tabindex - Continuing
create_LBL_files: 469 s (elapsed wall time)
ESC[?1lESC>error_code               = "0"   

> grep -C 0  RPCLAP_20160715_020746_615_USC.TAB    ro_create_delivery.EXT3.____._a__.__.2019-05-24_14.38.46.outerr.log
printing /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-05-22/RO-C-RPCLAP-5-EXT3-DERIV-V2.0/2016/JUL/D15/RPCLAP_20160715_020746_615_USC.TAB, mode: vz
--
printing /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-05-22/RO-C-RPCLAP-5-EXT3-DERIV-V2.0/2016/JUL/D15/RPCLAP_20160715_020746_615_USC.TAB, mode: vfloat
--
Exception.message    = "Expected existing regular file (or symlink to regular file) "/amd/nas24/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-05-22/RO-C-RPCLAP-5-EXT3-DERIV-V2.0/2016/JUL/D15/RPCLAP_20160715_020746_615_USC.TAB" can not be found."

> grep -C 0   RPCLAP_20160715_033202_417_USC.TAB   ro_create_delivery.EXT3.____._a__.__.2019-05-24_14.38.46.outerr.log
printing /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-05-22/RO-C-RPCLAP-5-EXT3-DERIV-V2.0/2016/JUL/D15/RPCLAP_20160715_033202_417_USC.TAB, mode: vz
--
printing /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-05-22/RO-C-RPCLAP-5-EXT3-DERIV-V2.0/2016/JUL/D15/RPCLAP_20160715_033202_417_USC.TAB, mode: vfloat
--
Exception.message    = "Expected existing regular file (or symlink to regular file) "/amd/nas24/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-05-22/RO-C-RPCLAP-5-EXT3-DERIV-V2.0/2016/JUL/D15/RPCLAP_20160715_033202_417_USC.TAB" can not be found."

**Comment by ErikPGJ** [comment]
EXT3
Verkar vara samma sak med två NED-filer efter att ha kört om createLBL (tidigare version/körning ignorerade NED_tabindex). Besläktat?



# createLBL
======== An exception has occurred ========
Exception.message    = "Expected existing regular file (or symlink to regular file) "/amd/nas24/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-05-22/RO-C-RPCLAP-5-EXT3-DERIV-V2.0/2016/JUL/D15/RPCLAP_20160715_020746_615_NED.TAB" can not be found."
Exception.identifier = ""
row 142, /amd/hem/export/home/erjo/lapdog_copy2/+EJ_library/+utils/assert.m: assert.file_exists
row 196, /amd/hem/export/home/erjo/lapdog_copy2/+createLBL/create_OBJTABLE_LBL_file.m: create_OBJTABLE_LBL_file
row 382, /amd/hem/export/home/erjo/lapdog_copy2/+createLBL/create_LBL_files.m: create_LBL_files
row 179, /amd/hem/export/home/erjo/lapdog_copy2/createLBL.m: createLBL
row 113, /home/erjo/matlab_copy/+erikpgjohansson/+ro/rerun_analysis_createLBL.m: rerun_analysis_createLBL___INTERNAL
row  34, /home/erjo/matlab_copy/+erikpgjohansson/+ro/rerun_analysis_createLBL.m: @()rerun_analysis_createLBL___INTERNAL(pdDatasetPath,ldDatasetPath,selectedSegments)
row 144, /home/erjo/matlab_copy/+erikpgjohansson/+ro/lapdog_convention_wrapper.m: call_function_pointer
row 125, /home/erjo/matlab_copy/+erikpgjohansson/+ro/lapdog_convention_wrapper.m: lapdog_convention_wrapper
row  33, /home/erjo/matlab_copy/+erikpgjohansson/+ro/rerun_analysis_createLBL.m: rerun_analysis_createLBL
Aborting LBL file for NED_tabindex - Continuing
======== An exception has occurred ========
Exception.message    = "Expected existing regular file (or symlink to regular file) "/amd/nas24/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-05-22/RO-C-RPCLAP-5-EXT3-DERIV-V2.0/2016/JUL/D15/RPCLAP_20160715_033202_417_NED.TAB" can not be found."
Exception.identifier = ""
row 142, /amd/hem/export/home/erjo/lapdog_copy2/+EJ_library/+utils/assert.m: assert.file_exists
row 196, /amd/hem/export/home/erjo/lapdog_copy2/+createLBL/create_OBJTABLE_LBL_file.m: create_OBJTABLE_LBL_file
row 382, /amd/hem/export/home/erjo/lapdog_copy2/+createLBL/create_LBL_files.m: create_LBL_files
row 179, /amd/hem/export/home/erjo/lapdog_copy2/createLBL.m: createLBL
row 113, /home/erjo/matlab_copy/+erikpgjohansson/+ro/rerun_analysis_createLBL.m: rerun_analysis_createLBL___INTERNAL
row  34, /home/erjo/matlab_copy/+erikpgjohansson/+ro/rerun_analysis_createLBL.m: @()rerun_analysis_createLBL___INTERNAL(pdDatasetPath,ldDatasetPath,selectedSegments)
row 144, /home/erjo/matlab_copy/+erikpgjohansson/+ro/lapdog_convention_wrapper.m: call_function_pointer
row 125, /home/erjo/matlab_copy/+erikpgjohansson/+ro/lapdog_convention_wrapper.m: lapdog_convention_wrapper
row  33, /home/erjo/matlab_copy/+erikpgjohansson/+ro/rerun_analysis_createLBL.m: rerun_analysis_createLBL
Aborting LBL file for NED_tabindex - Continuing

**Comment by ErikPGJ** [comment]
Still present (same USC.TAB files) in commit
* fa1182f Fredrik Johansson (2019-06-20 18:15:19 +0200) (HEAD -> master, origin/master, origin/HEAD) WOL final(?) update. I think CALIB2 is now finished

Found in EXT3.
Not found in any other science phase.


======== An exception has occurred ========
Exception.message    = "Expected existing regular file (or symlink to regular file) "/data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-06-20/RO-C-RPCLAP-5-EXT3-DERIV-V1.0/2016/JUL/D15/RPCLAP_20160715_020746_615_USC.TAB" can not be found."
Exception.identifier = ""
row 142, /amd/hem/export/home/erjo/lapdog_copy7/+EJ_library/+utils/assert.m: assert.file_exists
row 210, /amd/hem/export/home/erjo/lapdog_copy7/+EJ_library/+ro/create_OBJTABLE_LBL_file.m: create_OBJTABLE_LBL_file
row 276, /amd/hem/export/home/erjo/lapdog_copy7/+createLBL/create_LBL_files.m: create_LBL_files
row 180, /amd/hem/export/home/erjo/lapdog_copy7/createLBL.m: createLBL
row 122, /amd/hem/export/home/erjo/lapdog_copy7/lapdog.m: lapdog
row  60, /amd/hem/export/home/erjo/matlab_copy/+erikpgjohansson/+ro/run_lapdog.m: @()lapdog(calib1Path,missionPhaseNameAbbrev,pdsMissionCalendar)
row 207, /amd/hem/export/home/erjo/matlab_copy/+erikpgjohansson/+ro/lapdog_convention_wrapper.m: call_function_pointer
row 188, /amd/hem/export/home/erjo/matlab_copy/+erikpgjohansson/+ro/lapdog_convention_wrapper.m: lapdog_convention_wrapper
row  62, /amd/hem/export/home/erjo/matlab_copy/+erikpgjohansson/+ro/run_lapdog.m: run_lapdog
Aborting LBL file for USC_tabindex - Continuing
======== An exception has occurred ========
Exception.message    = "Expected existing regular file (or symlink to regular file) "/data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-06-20/RO-C-RPCLAP-5-EXT3-DERIV-V1.0/2016/JUL/D15/RPCLAP_20160715_033202_417_USC.TAB" can not be found."
Exception.identifier = ""
row 142, /amd/hem/export/home/erjo/lapdog_copy7/+EJ_library/+utils/assert.m: assert.file_exists
row 210, /amd/hem/export/home/erjo/lapdog_copy7/+EJ_library/+ro/create_OBJTABLE_LBL_file.m: create_OBJTABLE_LBL_file
row 276, /amd/hem/export/home/erjo/lapdog_copy7/+createLBL/create_LBL_files.m: create_LBL_files
row 180, /amd/hem/export/home/erjo/lapdog_copy7/createLBL.m: createLBL
row 122, /amd/hem/export/home/erjo/lapdog_copy7/lapdog.m: lapdog
row  60, /amd/hem/export/home/erjo/matlab_copy/+erikpgjohansson/+ro/run_lapdog.m: @()lapdog(calib1Path,missionPhaseNameAbbrev,pdsMissionCalendar)
row 207, /amd/hem/export/home/erjo/matlab_copy/+erikpgjohansson/+ro/lapdog_convention_wrapper.m: call_function_pointer
row 188, /amd/hem/export/home/erjo/matlab_copy/+erikpgjohansson/+ro/lapdog_convention_wrapper.m: lapdog_convention_wrapper
row  62, /amd/hem/export/home/erjo/matlab_copy/+erikpgjohansson/+ro/run_lapdog.m: run_lapdog
Aborting LBL file for USC_tabindex - Continuing

**Comment by frejon** [comment]
I can't seem to be able to reproduce this error on Matlab_R2015b.  commit https://github.com/irfu/Lapdog_GIT/commit/b973b1ed66f08af4d07d0577066ae71db265cca0

But I did find some bugs that will be fixed in the next commit. 

For future reference:

•Both RPCLAP_20160715_033202_417_USC.TAB and RPCLAP_20160715_020746_615_USC.TAB are files where LAP2 is in floating mode and in shadow (or otherwise not allowed to print USC/NED files).

•an_downsample sends LAP2 float data to an_USCprint. A file is created, nothing is printed, this is detected, the file deleted and usc_tabindex cleared.

•an_outputscience sends LAP1 Vz data to an_USCprint. A file is created, a few rows are written as normal.

•The "deleting duplicates in usc_tabindex " routine doesn't seem to find any duplicates here. since usc_tabindex was cleared.

...similarly for NED_tabindex.

Does the problem still exist? Is usc_tabindex not properly cleared in earlier versions of Matlab? 
A related bug was that I've missed closing some USC & NED Vz files. This should've caused more problems, but somehow it didn't?

**Comment by ErikPGJ** [comment]
A fresh new EXT3 should be complete by tomorrow morning. We can see if we get the problem again then.

**Comment by ErikPGJ** [comment]
Unfortunately, still has problem for complete rerun.
Commit * b973b1e Fredrik Johansson (2019-06-25 11:08:39 +0200) EFL update for Action 41695
MATLAB  R2016a
Found in EXT3.
Not found in ASTx, ESC1.


======== An exception has occurred ========
Exception.message    = "Expected existing regular file (or symlink to regular file) "/data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-06-25/RO-C-RPCLAP-5-EXT3-DERIV-V1.0/2016/JUL/D15/RPCLAP_20160715_020746_615_USC.TAB" can not be found."
Exception.identifier = ""
row 142, /amd/hem/export/home/erjo/lapdog_copy7/+EJ_library/+utils/assert.m: assert.file_exists
row 210, /amd/hem/export/home/erjo/lapdog_copy7/+EJ_library/+ro/create_OBJTABLE_LBL_file.m: create_OBJTABLE_LBL_file
row 276, /amd/hem/export/home/erjo/lapdog_copy7/+createLBL/create_LBL_files.m: create_LBL_files
row 180, /amd/hem/export/home/erjo/lapdog_copy7/createLBL.m: createLBL
row 122, /amd/hem/export/home/erjo/lapdog_copy7/lapdog.m: lapdog
row  60, /amd/hem/export/home/erjo/matlab_copy/+erikpgjohansson/+ro/run_lapdog.m: @()lapdog(calib1Path,missionPhaseNameAbbrev,pdsMissionCalendar)
row 207, /amd/hem/export/home/erjo/matlab_copy/+erikpgjohansson/+ro/lapdog_convention_wrapper.m: call_function_pointer
row 188, /amd/hem/export/home/erjo/matlab_copy/+erikpgjohansson/+ro/lapdog_convention_wrapper.m: lapdog_convention_wrapper
row  62, /amd/hem/export/home/erjo/matlab_copy/+erikpgjohansson/+ro/run_lapdog.m: run_lapdog
Aborting LBL file for USC_tabindex - Continuing
======== An exception has occurred ========
Exception.message    = "Expected existing regular file (or symlink to regular file) "/data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-06-25/RO-C-RPCLAP-5-EXT3-DERIV-V1.0/2016/JUL/D15/RPCLAP_20160715_033202_417_USC.TAB" can not be found."
Exception.identifier = ""
row 142, /amd/hem/export/home/erjo/lapdog_copy7/+EJ_library/+utils/assert.m: assert.file_exists
row 210, /amd/hem/export/home/erjo/lapdog_copy7/+EJ_library/+ro/create_OBJTABLE_LBL_file.m: create_OBJTABLE_LBL_file
row 276, /amd/hem/export/home/erjo/lapdog_copy7/+createLBL/create_LBL_files.m: create_LBL_files
row 180, /amd/hem/export/home/erjo/lapdog_copy7/createLBL.m: createLBL
row 122, /amd/hem/export/home/erjo/lapdog_copy7/lapdog.m: lapdog
row  60, /amd/hem/export/home/erjo/matlab_copy/+erikpgjohansson/+ro/run_lapdog.m: @()lapdog(calib1Path,missionPhaseNameAbbrev,pdsMissionCalendar)
row 207, /amd/hem/export/home/erjo/matlab_copy/+erikpgjohansson/+ro/lapdog_convention_wrapper.m: call_function_pointer
row 188, /amd/hem/export/home/erjo/matlab_copy/+erikpgjohansson/+ro/lapdog_convention_wrapper.m: lapdog_convention_wrapper
row  62, /amd/hem/export/home/erjo/matlab_copy/+erikpgjohansson/+ro/run_lapdog.m: run_lapdog
Aborting LBL file for USC_tabindex - Continuing

**Comment by ErikPGJ** [comment]
This looks tentatively resolved judging from rerun of EXT3 after FJ's bugfix.

* e76b3cf Erik P G Johansson (2019-06-26 15:56:20 +0200) (HEAD -> master, origin/master, origin/HEAD) LBL: EJ_library sync; somewhat better error handling
