### ISSUE TITLE
NEL_tabindex lacks large subset of NEL.TAB files

### ISSUE THREAD

**Issue by ErikPGJ** [frejon/Lapdog_GIT#34]
* fa1182f Fredrik Johansson (2019-06-20 18:15:19 +0200) (HEAD -> master, origin/master, origin/HEAD) WOL final(?) update. I think CALIB2 is now finished

Found in all comet phases.

Lack of NEL.LBL files indicates that NEL_tabindex lacks a large subset of NEL.TAB files.
Not to be confused with issue #29 (same for NED).

erjo@spis /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-06-20> l RO-*-5-*/*/*/*/*NEL.TAB | wc -l
1386
erjo@spis /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-06-20> l RO-*-5-*/*/*/*/*NEL.LBL | wc -l
758

**Comment by frejon** [comment]
Not sure this is a bug

in the same folder:

ls RO*-5-*/*/*/*/*32S_NEL.TAB | wc -l
627
758+627 = 1385 ≈  1386.  
32S_NEL.TAB files are not for archiving. I can disable them if you want.

**Comment by ErikPGJ** [comment]
You seem to be correct. Forgot that 32S_NEL.TAB should not have any LBL files.

You do not need to deactivate 32S_NEL.TAB. All my pipeline code (Lapsus etc) knows to expect and ignore them. Just I who don't know...
