### ISSUE TITLE
Error at loop step 27 or  foutarr{}(0) -- MATLAB:cellRefFromNonCell

### ISSUE THREAD

**Issue by ErikPGJ** [frejon/Lapdog_GIT#43]
* 9219c27 Fredrik Johansson (2019-07-01 22:20:02 +0200) (HEAD -> master, origin/master, origin/HEAD) Give up on orbit_v2, back to something that actually works!

Found in ESC1, ESC2, EXT2, PRL.
Not found in EXT3.

################################################################################
printing /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-06-26/RO-C-RPCLAP-5-ESC1-DERIV-V2.0/2015/MAR/D08/RPCLAP_20150308_000245_805_NEL.TAB, mode: Ion
printing /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-06-26/RO-C-RPCLAP-5-ESC1-DERIV-V2.0/2015/MAR/D09/RPCLAP_20150309_000000_805_NEL.TAB, mode: Ion
printing /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-06-26/RO-C-RPCLAP-5-ESC1-DERIV-V2.0/2015/MAR/D10/RPCLAP_20150310_000213_805_NEL.TAB, mode: Ion
Error at loop step 27 or  foutarr{}(0), file /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-06-26/RO-C-RPCLAP-5-ESC1-DERIV-V2.0/2014/DEC/D13/RPCLAP_20141213_000315_525_I2L.TAB
ans =

MATLAB:cellRefFromNonCell

ans =

Cell contents reference from a non-cell array object.

an_NEL, 71,analysis, 105,rerun_analysis_createLBL___INTERNAL, 106,@()rerun_analysis_createLBL___INTERNAL(pdDatasetPath,ldDatasetPath,selectedSegments), 35,call_function_pointer, 207,lapdog_convention_wrapper, 188,rerun_analysis_createLBL, 34,Error at loop step 2 or  foutarr{}(0), file /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-06-26/RO-C-RPCLAP-5-ESC1-DERIV-V2.0/2014/DEC/D05/RPCLAP_20141205_214851_503_V2L.TAB
ans =

MATLAB:cellRefFromNonCell

ans =

Cell contents reference from a non-cell array object.

an_NEL, 71,analysis, 115,rerun_analysis_createLBL___INTERNAL, 106,@()rerun_analysis_createLBL___INTERNAL(pdDatasetPath,ldDatasetPath,selectedSegments), 35,call_function_pointer, 207,lapdog_convention_wrapper, 188,rerun_analysis_createLBL, 34,Generating spectra
Saving MATLAB workspace+globals

########################################################################

printing /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-06-26/RO-C-RPCLAP-5-PRL-DERIV-V2.0/2014/NOV/D10/RPCLAP_20141110_000000_803_NEL.TAB, mode: Ion
printing /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-06-26/RO-C-RPCLAP-5-PRL-DERIV-V2.0/2014/NOV/D14/RPCLAP_20141114_100314_807_NEL.TAB, mode: Ion
printing /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-06-26/RO-C-RPCLAP-5-PRL-DERIV-V2.0/2014/NOV/D18/RPCLAP_20141118_090258_803_NEL.TAB, mode: Ion
Error at loop step 4 or  foutarr{}(0), file /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-06-30_DERIV_science_mp/gen_2019-04-17/gen_2019-06-26/RO-C-RPCLAP-5-PRL-DERIV-V2.0/2014/MAR/D24/RPCLAP_20140324_162131_504_V2L.TAB
ans =

MATLAB:cellRefFromNonCell

ans =

Cell contents reference from a non-cell array object.

an_NEL, 71,analysis, 115,rerun_analysis_createLBL___INTERNAL, 106,@()rerun_analysis_createLBL___INTERNAL(pdDatasetPath,ldDatasetPath,selectedSegments), 35,call_function_pointer, 207,lapdog_convention_wrapper, 188,rerun_analysis_createLBL, 34,Generating spectra
Saving MATLAB workspace+globals

**Comment by frejon** [comment]
My suspicion is that this issue only exists if you rerun lapdog from a saved state from an older commit. Nevertheless, I've commited something that will clear this issue regardless
