### ISSUE TITLE
Harmless? -- lapdog:Analysis Error for /.../_I1S.TAB; error message:Matrix dimensions must agree

### ISSUE THREAD

**Issue by ErikPGJ** [frejon/Lapdog_GIT#48]
fe746c4 Fredrik Johansson (2019-09-05 17:01:52 +0200) (HEAD -> master, origin/master, origin/HEAD) Lapdog test update after RIDS.

ESC4
Harmless, legitimate analysis fail that can be expected? (Compare #46?)

=====================================
lapdog:Analysis Error for /amd/nas24/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-10-31_L235_comet/2019-09-05/RO-C-RPCLAP-5-ESC4-DERIV-V1.0/2015/DEC/D30/RPCLAP_20151230_080205_827_I1S.TAB, 
Vguess= 0.000000 , illum=1.0
 error message:Matrix dimensions must agree.
sweepFilterChooser_test, 41,an_LP_Sweep_v2, 151,an_sweepmain_v2, 413,analysis, 60,lapdog, 117,@()lapdog(calib1Path,missionPhaseNameAbbrev,pdsMissionCalendar), 60,call_function_pointer, 207,lapdog_convention_wrapper, 188,run_lapdog, 62,V & I = 
-2.860300e+01,-2.836100e+01,-2.812100e+01,-2.788000e+01,-2.764100e+01,-2.739900e+01,-2.715900e+01,-2.691800e+01,-2.668200e+01,-2.644000e+01,-2.620000e+01,-2.595900e+01,-2.572000e+01,-2.547800e+01,-2.523800e+01,-2.499700e+01,-2.475700e+01,-2.451600e+01,-2.427600e+01,-2.403400e+01,-2.379500e+01,-2.355300e+01,-2.331300e+01,-2.307200e+01,-2.284000e+01,-2.259900e+01,-2.235900e+01,-2.211700e+01,-2.187800e+01,-2.163700e+01,-2.139600e+01,-2.115500e+01,-2.091500e+01,-2.067400e+01,-2.043400e+01,-2.019200e+01,-1.995970e+01,-1.971810e+01,-1.947780e+01,-1.923650e+01,-1.900080e+01,-1.875920e+01,-1.851900e+01,-1.827760e+01,-1.803840e+01,-1.779680e+01,-1.755660e+01,-1.731520e+01,-1.707510e+01,-1.683360e+01,-1.659330e+01,-1.635190e+01,-1.611260e+01,-1.587110e+01,-1.563080e+01,-1.538940e+01,-1.516680e+01,-1.492530e+01,-

**Comment by frejon** [comment]
Harmless
