### ISSUE TITLE
Undefined function or variable 'idmin11'.

### ISSUE THREAD

**Issue by ErikPGJ** [frejon/Lapdog_GIT#49]
* 4467571 Fredrik Johansson (2019-09-12 09:59:10 +0200) (HEAD -> master, origin/master, origin/HEAD) Fix for issue #47 , bugfixes, improvements

ESC1-3; probably all mission phases.

/amd/nas24/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-10-31_L35_comet/2019-09-12/ro_pipeline.ESC1.____._LO.__.___.__.2019-09-12_14.48.32.outerr.log

====================================================================
Macroblock 1 out of  187.
 Latest file created from 2014-11-19T23:59:58.257

lapdog:createTAB error message:Undefined function or variable 'idmin11'.
createTAB, 229,process, 94,lapdog, 103,@()lapdog(calib1Path,missionPhaseNameAbbrev,pdsMissionCalendar), 60,call_function_pointer, 207,lapdog_convention_wrapper, 188,run_lapdog, 62,
lapdog: skipping file, continuing...

lapdog:createTAB error message:Undefined function or variable 'idmin11'.
createTAB, 229,process, 95,lapdog, 103,@()lapdog(calib1Path,missionPhaseNameAbbrev,pdsMissionCalendar), 60,call_function_pointer, 207,lapdog_convention_wrapper, 188,run_lapdog, 62,
lapdog: skipping file, continuing...
=======================================================================
Later is presumebly a consequence of the above
=======================================================================
Downsampling low frequency measurements
Error at loop step 2 or  foutarr{}(0), file /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-10-31_L35_comet/2019-09-12/RO-C-RPCLAP-5-ESC1-DERIV-V2.0/2014/NOV/D20/RPCLAP_20141120_000000_515_I1L.TAB
ans =

MATLAB:badsubscript

ans =

Index exceeds matrix dimensions.

an_NEL, 91,analysis, 99,lapdog, 117,@()lapdog(calib1Path,missionPhaseNameAbbrev,pdsMissionCalendar), 60,call_function_pointer, 207,lapdog_convention_wrapper, 188,run_lapdog, 62,Error at loop step 2 or  foutarr{}(2700), file /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-10-31_L35_comet/2019-09-12/RO-C-RPCLAP-5-ESC1-DERIV-V2.0/2014/NOV/D20/RPCLAP_20141120_000000_515_I1L.TAB
ans =

MATLAB:badsubscript

ans =

Index exceeds matrix dimensions.

an_downsample, 113,analysis, 101,lapdog, 117,@()lapdog(calib1Path,missionPhaseNameAbbrev,pdsMissionCalendar), 60,call_function_pointer, 207,lapdog_convention_wrapper, 188,run_lapdog, 62,printing /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-10-31_L35_comet/2019-09-12/RO-C-RPCLAP-5-ESC1-DERIV-V2.0/2014/DEC/D13/RPCLAP_20141213_000315_525_NEL.TAB, mode: Ion
Error at loop step 28 or  foutarr{}(0), file /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2019-10-31_L35_comet/2019-09-12/RO-C-RPCLAP-5-ESC1-DERIV-V2.0/2014/DEC/D14/RPCLAP_20141214_000003_525_I2L.TAB

**Comment by frejon** [comment]
Doesn't seem to exist
