### ISSUE TITLE
MICE: The body name CHECK could not be translated to a NAIF ID code

### ISSUE THREAD

**Issue by ErikPGJ** [frejon/Lapdog_GIT#52]
Can not (presumably) do analysis on CVP1, CVP2. No error for all other non-comet phases. Does not seem to hurt actual PSA deliveries since analysis (DERIV2, NEL) is not delivered for non-comet phases, but it is a problem for producing IRFU-internal, inofficial DERIV2+NEL for non-comet phases.

Footnote: I have upgraded to the latest MICE version, v66 (from MICE v65 for previous delivieries) since that was required for reading updated SPICE kernels. MICE version should thus not be the problem.

--------------------------------------------------------------------
Macroblock 43 out of  43.
 Latest file created from 2004-05-10T02:02:25.203                                                                   
Saving MATLAB workspace+globals
    Saving MATLAB variable "index" (12547960 bytes) in "/data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2021-0x-xx_L3_noncomet/2021-04-21_19.53_all/RO-X-RPCLAP-5-CVP1-DERIV-V2.0/pre_analysis_workspace.index.*"
    Done saving variables to disk: 6 s (elapsed wall time)
Analysing sweeps
Error at loop step 1, file /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2021-0x-xx_L3_noncomet/2021-04-21_19.53_all/RO-X-RPCLAP-5-CVP1-DERIV-V2.0/2004/MAR/D17/RPCLAP_20040317_235742_204_I1S.TAB
 Error at loop step k=0,
ans =

     ''

ans =

Error using mice
SPICE(NOTRANSLATION): [bodvrd_c->BODVRD] The body name CHECK could not be translated to a NAIF ID code.  The cause of this problem may be that you need an updated version of the SPICE Toolkit.

cspice_bodvrd, 218; orbit, 103; an_sweepmain_v2, 157; analysis, 60; lapdog, 117; @()lapdog(calib1Path,missionPhaseNameAbbrev,pdsMissionCalendar), 60; call_function_pointer, 207; lapdog_convention_wrapper, 188; run_lapdog, 62; Outputting Science
Error: an empty XXP was loaded, or no sweeps were analysed. aborting
Downsampling low frequency measurements
Generating spectra
lapdog: generate LBL files....
Saving MATLAB workspace+globals
    Saving MATLAB variable "index" (12547960 bytes) in "/data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2021-0x-xx_L3_noncomet/2021-04-21_19.53_all/RO-X-RPCLAP-5-CVP1-DERIV-V2.0/pre_createLBL_workspace.index.*"
    Done saving variables to disk: 6 s (elapsed wall time)
Note: Requested variable does not exist in the caller workspace: "ASW_tabindex"
Note: Requested variable does not exist in the caller workspace: "PHO_tabindex"
Note: Requested variable does not exist in the caller workspace: "efl_tabindex"
create_LBL_files: 39 s (elapsed wall time)
lapdog: DONE!
error_code                  = "0"

**Comment by frejon** [comment]
Corrected in commit f53d1ba
TBC

**Comment by ErikPGJ** [comment]
Is this fixed or not?
Re-running the analysis on brain for CVP1 yields the same error message.

---------------------------------------------------------------------------------------
Analysing sweeps
Error at loop step 1, file /data/rosetta/PDS_Archives/DATASETS/delivery/delivery_2021-0x-xx_L3_noncomet/2021-04-28_17.06_precomet_PRL/RO-X-RPCLAP-5-CVP1-DERIV-V2.0/2004/MAR/D17/RPCLAP_20040317_235742_204_I1S.TAB
 Error at loop step k=0,
ans =

     ''



ans =

Error using mice
SPICE(NOTRANSLATION): [bodvrd_c->BODVRD] The body name CHECK could not be translated to a NAIF ID code.  The cause of this problem may be that you need an updated version of the SPICE Toolkit.

cspice_bodvrd, 218; orbit, 103; an_sweepmain_v2, 157; analysis, 60; rerun_analysis_createLBL___INTERNAL, 106; @()rerun_analysis_createLBL___INTERNAL(pdDatasetPath,ldDatasetPath,selectedSegments), 35; call_function_pointer, 207; lapdog_convention_wrapper, 188; rerun_analysis_createLBL, 34; Outputting Science
Error: an empty XXP was loaded, or no sweeps were analysed. aborting
Downsampling low frequency measurements
Generating spectra
Saving MATLAB workspace+globals
    Saving MATLAB variable "index" (12685120 bytes) in "/amd/nas24/rosetta/PDS_Archives/DATASETS/delivery/delivery_2021-0x-xx_L3_noncomet/2021-04-28_17.06_precomet_PRL/RO-X-RPCLAP-5-CVP1-DERIV-V2.0/pre_createLBL_workspace.index.*"
    Done saving variables to disk: 6 s (elapsed wall time)

**Comment by frejon** [comment]
Yes it is, but if lapdog isn't run, preamble isn't run, and therefore
incorrect globals are in the workspace of old runs.

You could try to run preamble as a first thing in RERUN_ANALYSIS_CREATELBL,
or wherever you think is suitable

**Comment by ErikPGJ** [comment]
I realized that too after some debugging too. Re-running now.

**Comment by ErikPGJ** [comment]
Re-running CVP1&2 DERIV1 seems OK.
