### ISSUE TITLE
Undefined function or variable "dark_ind_1"

### ISSUE THREAD

**Issue by ErikPGJ** [frejon/Lapdog_GIT#9]
Inträffar för endagsarkiv 2016-07-30 men inte för arkiv 2016-02-26, eller 2016-02-25--27 (feb 25-27),
commit 8d8ff24

Analysing sweeps
 Analysing LAP2 sweeps
8 NaN in a row. Give up

lapdog:Analysis Error for /home/data/ROSETTA/datasets/EXT3_2016-07-30/RO-C-RPCLAP-5-EXT3-DERIV-V0.1/2016/JUL/D30/RPCLAP_20160730_000001_416_I2S.TAB, 
Vguess= 0.000000 , illum=0.0
 error message:Matrix dimensions must agree.
sweepFilterChooser_test, 41,an_LP_Sweep_v2, 151,an_sweepmain_v2, 413,analysis, 59,main, 110,V & I = 
-2.863300e+01,-2.839100e+01,-2.815100e+01,-2.791000e+01,-2.766900e+01,-2.742800e+01,-2.718800e+01,-2.694600e+01,-2.671000e+01,-2.646900e+01,-2.622800e+01,-2.598700e+01,-2.574700e+01,-2.550500e+01,-2.526500e+01,-2.502400e+01,-2.478500e+01,-2.454400e+01,-2.430300e+01,-2.406200e+01,-2.382200e+01,-2.358000e+01,-2.334000e+01,-2.309900e+01,-2.286900e+01,-2.262800e+01,-2.238700e+01,-2.214600e+01,-2.190600e+01,-2.166400e+01,-2.142400e+01,-2.118300e+01,-2.094400e+01,-2.070300e+01,-2.046200e+01,-2.022100e+01,-1.998690e+01,-1.974550e+01,-1.950520e+01,-1.926390e+01,-1.902740e+01,-1.878590e+01,-1.854560e+01,-1.830430e+01,-1.806380e+01,-1.782240e+01,-1.758210e+01,-1.734090e+01,-1.710190e+01,-1.686050e+01,-1.662010e+01,-1.637880e+01,-1.613830e+01,-1.589690e+01,-1.565650e+01,-1.541530e+01,-1.517500e+01,-1.493350e+01,-1.469320e+01,-1.445190e+01,-1.421130e+01,-1.396990e+01,-1.372970e+01,-1.348840e+01,-1.324950e+01,-1.300810e+01,-1.276770e+01,-1.252640e+01,-1.228590e+01,-1.204450e+01,-1.180420e+01,-1.156290e+01,-1.132640e+01,-1.108490e+01,-1.084460e+01,-1.060330e+01,-1.036280e+01,-1.012140e+01,-9.881000e+00,-9.639800e+00,-9.400900e+00,-9.159500e+00,-8.919100e+00,-8.677800e+00,-8.437300e+00,-8.195900e+00,-7.955600e+00,-7.714300e+00,-7.483900e+00,-7.242500e+00,-7.002100e+00,-6.760800e+00,-6.520300e+00,-6.278900e+00,-6.038600e+00,-5.797400e+00,-5.558400e+00,-5.317000e+00,-5.076700e+00,-4.835400e+00,-4.594800e+00,-4.353400e+00,-4.113000e+00,-3.871700e+00,-3.635100e+00,-3.393600e+00,-3.153300e+00,-2.912000e+00,-2.671500e+00,-2.430100e+00,-2.189800e+00,-1.949320e+00,-1.710210e+00,-1.468660e+00,-1.228210e+00,-9.867800e-01,-7.460600e-01,-5.045700e-01,-2.640800e-01,-2.266000e-02,2.270000e-01,4.685000e-01,7.088900e-01,9.503000e-01,1.190880e+00,1.432350e+00,1.672720e+00,1.914130e+00,2.152100e+00,2.393500e+00,2.633800e+00,2.875100e+00,3.115700e+00,3.357100e+00,3.597400e+00,3.838800e+00,4.075500e+00,4.316800e+00,4.557100e+00,4.798500e+00,5.039000e+00,5.280300e+00,5.520600e+00,5.762000e+00,6.000800e+00,6.242300e+00,6.482600e+00,6.723900e+00,6.964500e+00,7.205900e+00,7.446200e+00,7.687600e+00,7.918000e+00,8.159300e+00,8.399600e+00,8.641000e+00,8.881500e+00,9.122800e+00,9.363200e+00,9.604500e+00,9.843400e+00,1.008470e+01,1.032500e+01,1.056630e+01,1.080700e+01,1.104830e+01,1.128870e+01,1.153010e+01,1.176700e+01,1.200840e+01,1.224870e+01,1.249010e+01,1.273060e+01,1.297190e+01,1.321230e+01,1.345370e+01,1.369270e+01,1.393410e+01,1.417440e+01,1.441580e+01,1.465640e+01,1.489780e+01,1.513820e+01,1.537960e+01,1.562060e+01,1.586190e+01,1.610220e+01,1.634350e+01,1.658390e+01,1.682530e+01,1.706560e+01,1.730690e+01,1.754580e+01,1.778710e+01,1.802750e+01,1.826880e+01,1.850940e+01,1.875070e+01,1.899110e+01,1.923250e+01,1.946940e+01,1.971080e+01,1.995110e+01,2.019250e+01,2.043300e+01,2.067430e+01,2.091470e+01,2.114900e+01,2.138800e+01,2.162900e+01,2.186900e+01,2.211100e+01,2.235100e+01,2.259300e+01,2.283300e+01,2.307400e+01,2.330500e+01,2.354600e+01,2.378700e+01,2.402800e+01,2.426800e+01,2.451000e+01,2.475000e+01,2.499100e+01,2.523000e+01,2.547100e+01,2.571200e+01,2.595300e+01,2.619300e+01,2.643500e+01,2.667500e+01,2.691600e+01,2.715400e+01,2.739500e+01,2.763500e+01,2.787600e+01,2.811700e+01,2.835800e+01,2.859900e+01,2.884000e+01,
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.001930e-05,-1.000369e-05,-9.994180e-06,-9.961172e-06,-9.997744e-06,-9.983960e-06,-9.970176e-06,-9.852629e-06,-9.892555e-06,-9.905319e-06,-9.845450e-06,-9.877744e-06,-9.856631e-06,-9.856879e-06,-9.825694e-06,-9.852797e-06,-9.819474e-06,-9.864887e-06,-9.826069e-06,-9.846761e-06,-9.793294e-06,-9.799946e-06,-9.767535e-06,-9.791276e-06,-9.805556e-06,-9.828381e-06,-9.833199e-06,-9.823368e-06,-9.824523e-06,-9.967587e-06,-9.843006e-06,-9.831342e-06,-9.958230e-06,-9.956636e-06,-9.830222e-06,-9.828627e-06,-9.858160e-06,-9.808956e-06,-9.793626e-06,-9.865883e-06,-9.790127e-06,-9.802568e-06,-9.898628e-06,-9.874751e-06,-9.840498e-06,-9.766877e-06,-9.751849e-06,-9.813727e-06,-9.744071e-06,-9.844706e-06,-9.876675e-06,-9.795117e-06,-9.741025e-06,-9.837081e-06,-9.856842e-06,-9.753004e-06,-9.818236e-06,-9.887741e-06,-9.853789e-06,-9.904982e-06,-9.962889e-06,-9.959454e-06,-9.949916e-06,-9.898263e-06,-1.001049e-05,-1.001621e-05,-9.913897e-06,-9.903443e-06,-9.828900e-06,-9.735436e-06,-9.733526e-06,-9.772511e-06,-9.744355e-06,-9.761366e-06,-9.731990e-06,-9.831399e-06,-9.789816e-06,-9.841312e-06,-9.703902e-06,-9.724880e-06,-9.732430e-06,-9.761343e-06,-9.718234e-06,-9.781937e-06,-9.728757e-06,-9.738444e-06,-9.685569e-06,-9.779791e-06,-9.735766e-06,-9.699066e-06,-9.742323e-06,-9.735836e-06,-9.692422e-06,-9.700279e-06,-9.670903e-06,-9.623523e-06,-9.595369e-06,-9.576065e-06,-9.581786e-06,-9.614363e-06,-9.595671e-06,-9.562635e-06,-9.544248e-06,-9.480389e-06,-9.562712e-06,-9.508620e-06,-9.498168e-06,-9.540208e-06,-9.490389e-06,-9.517476e-06,-9.490546e-06,-9.485590e-06,-9.451031e-06,-9.438751e-06,-9.431049e-06,-9.430367e-06,-9.450742e-06,-9.394212e-06,-9.407875e-06,-9.315029e-06,-9.343951e-06,-9.273690e-06,-9.305970e-06,-9.258293e-06,-9.208786e-06,-9.203530e-06,-9.191866e-06,-9.187527e-06,-9.155722e-06,-9.140703e-06,-9.084789e-06,-9.072213e-06,-9.050786e-06,-9.009828e-06,-8.966735e-06,-8.936155e-06,-8.910153e-06,-8.846919e-06,-8.788570e-06,-8.785458e-06,-8.717649e-06,-8.667541e-06,-8.639712e-06,-8.538335e-06,-8.497689e-06,-8.454908e-06,-8.384052e-06,-8.295190e-06,-8.278962e-06,-8.220314e-06,-8.070113e-06,-8.034051e-06,-7.925051e-06,-7.895399e-06,-7.742760e-06,-7.743627e-06,-7.634630e-06,-7.522583e-06,-7.435255e-06,-7.219753e-06,-7.069255e-06,-6.768915e-06,-6.526254e-06,-6.255518e-06,-5.835244e-06,-5.561763e-06,-5.078013e-06,-4.730985e-06,-4.336351e-06,-3.964300e-06,-3.626125e-06,-3.316944e-06,-3.009289e-06,-2.662878e-06,-2.439760e-06,-2.050015e-06,-1.757013e-06,-1.528100e-06,-1.113028e-06,-6.283756e-07,-4.528724e-07,-1.537722e-07,-7.074079e-08,8.721129e-08,7.868633e-08,1.992516e-07,1.461680e-07,9.857653e-08,-2.271718e-08,-9.380986e-08,-1.645986e-07,-9.897277e-08,-9.468945e-08,-9.742650e-08,-1.096254e-07,-1.199944e-07,-2.660328e-08,1.124372e-08,8.281190e-08,6.801274e-08,
lapdog: continuing analysis...Outputting Science
Error: an empty XXP was loaded, or no sweeps were analysed. aborting
Downsampling low frequency measurements
Error at loop step 1 or  foutarr{}(2700), file /home/data/ROSETTA/datasets/EXT3_2016-07-30/RO-C-RPCLAP-5-EXT3-DERIV-V0.1/2016/JUL/D29/RPCLAP_20160729_235915_416_V1L.TAB
ans =

MATLAB:UndefinedFunction

ans =

Undefined function or variable "dark_ind_1".

an_downsample, 530,analysis, 107,main, 110,Generating spectra

ans =

lapdog: generate LBL files....

Saving pre-createLBL MATLAB workspace+globals in "/home/data/ROSETTA/datasets/EXT3_2016-07-30/RO-C-RPCLAP-5-EXT3-DERIV-V0.1/pre_createLBL_workspace.mat"
    Done: 0 s (elapsed wall time)

**Comment by frejon** [comment]
Fixed in latest commit
